name: Scheduled Jobs

on:
  push:
    branches:
      - "main"

permissions:
  contents: write
  pull-requests: write


jobs:
  make_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
    
      - name: write file
        run: |
          cat <<EOF > test.txt
          hello, world!
          EOF

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout test
          git pull --rebase origin test
          git add .
          git commit -m "Commit message"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push changes
        run: git push --set-upstream origin test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: make pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: test
          base: main
          title: "[Auto] Extract Testing Updates"
          body: |
            This PR includes the following changes:
            ```
            $(git diff HEAD~1 HEAD || echo "No changes detected.")
            ```
        
