name: Scheduled Jobs

on:
  push:
    branches:
      - "main"

permissions:
  contents: write
  pull-requests: write


jobs:
  make_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
    
      - name: write file
        run: |
          cat <<EOF > test.txt
          hello, world!
          EOF

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply test.txt changes
      
      - name: make pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: test
          base: main
          title: "[Auto] Extract Testing Updates"
          body: |
            This PR includes the following changes:
            ```
            $(git diff HEAD~1 HEAD || echo "No changes detected.")
            ```
        
