name: Auto Commit and Create PR

on:
  push:
    branches:
      - main

jobs:
  auto-commit-and-pr:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 변경 사항 생성 및 스테이징
      - name: Create and stage changes
        run: |
          echo "This is a test file created by GitHub Actions." > testing.txt
          git add testing.txt

      # 3. 상태 확인 (디버깅용)
      - name: Check git status
        run: git status

      # 4. 자동 커밋 실행
      - name: Auto commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto commit changes"
          branch: auto-update-branch  # 새로운 브랜치 이름 지정
          create_branch: true

      # 5. 강제 푸시 (변경 사항 누락 방지)
      - name: Force push changes
        run: git push --force-with-lease origin auto-update-branch

      # 6. Pull Request 생성
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: auto-update-branch  # 위에서 생성된 브랜치 이름 사용
          base: main                 # PR의 대상 브랜치 설정
          title: Automated Pull Request
          body: |
            This PR includes automated changes made by GitHub Actions.
