name: Auto Commit and Create PR

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create and stage changes
        run: |
          echo "This is a test file created by GitHub Actions." > testing.txt
          git add testing.txt

      - name: Check git status
        run: git status

      - name: Auto commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto commit changes"
          branch: auto-update-branch  
          create_branch: true

  pr:
    runs-on: ubuntu-latest
    needs: auto-commit

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: auto-update-branch
          base: main                 
          title: Automated Pull Request
          body: |
            This PR includes automated changes made by GitHub Actions.
