name: Auto Commit and Create PR

on:
  push:
    branches:
      - main  # main 브랜치에서만 트리거

jobs:
  auto-commit-and-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # GITHUB_TOKEN에 쓰기 권한 부여
      pull-requests: write  # PR 생성을 위한 권한

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Write File
        run: |
          cat << EOF > testing.txt
          new world
          EOF

      # 2. 변경 사항 자동 커밋
      - name: Auto commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto commit changes"
          branch: auto-update-branch  # 새로운 브랜치 이름 지정
          create_branch: true

      # 3. Pull Request 생성
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto commit changes"
          branch: auto-update-branch  # 위에서 생성한 브랜치 이름
          base: main  # PR의 대상 브랜치
          title: "Automated Pull Request"
          body: |
            This PR is automatically generated by GitHub Actions.
